### ISSUE TITLE
Box

### ISSUE THREAD

**Issue by netliteIT** [cod3monk/zpl#11]
def draw_ellipse(self, width, height, thickness=1, color='B'):
        assert color in 'BW', "invalid color"
        self.code += "^GE,%i,%i,%i,%c" % (width, height, thickness, color)

    def print_graphic(self, name, scale_x=1, scale_y=1):
        self.code += "^XG,%s,%i,%i" % (name, scale_x, scale_y)

Can't write boxes just rectangles.

    def draw_ellipse(self, width, height, thickness=1, color='B'):
        assert color in 'BW', "invalid color"
        self.code += "^GE%i,%i,%i,%c" % (width, height, thickness, color)

    def print_graphic(self, name, scale_x=1, scale_y=1):
        self.code += "^XG%s,%i,%i" % (name, scale_x, scale_y)

Isn't much correct without , ?

^GE80,80,1

instead of

^GE,80,80,1

**Comment by cod3monk** [comment]
Your are correct.

**Comment by cod3monk** [comment]
Thanks for reporting this bug :)
