### ISSUE TITLE
Adding Qr Code

### ISSUE THREAD

**Issue by Noah2345** [cod3monk/zpl#14]
Hello,

could you please add Barcode type "Q" for QR-Codes in the write_barcode Function?

Thank you!

**Comment by cod3monk** [comment]
Done, let me know if it works for you.

**Comment by Noah2345** [comment]
@cod3monk The Qr-Code generation works. The errorCorrection and mask attributes do not seem to do anything, but I think those aren't really important. 
Thank you!
