### ISSUE TITLE
Issue with encoding

### ISSUE THREAD

**Issue by Noah2345** [cod3monk/zpl#15]
@cod3monk Hey, we ran into another issue with the iso8859-1 encoding in the TCPPrinter class. We could not print any foreign language symbols. (ü,ä, à, °). We changed the encoding to utf-8 and it worked. Tested with zebra zd420.

**Comment by cod3monk** [comment]
can you check the latest commit?

**Comment by Noah2345** [comment]
@cod3monk Yes, that works. Thank you!
