### ISSUE TITLE
Barcode Types

### ISSUE THREAD

**Issue by Noah2345** [cod3monk/zpl#18]
@cod3monk could you add the option for an EAN13 Barcode. That would be ^BE.
Here is the reference in the zpl manual. Page 96
https://www.zebra.com/content/dam/zebra/manuals/printers/common/programming/zpl-zbi2-pm-en.pdf
Thank you!

**Comment by cod3monk** [comment]
Resolved with 17802d90a4b6eb8f6a6aabf0cf708b1c6075a319
