### ISSUE TITLE
Ideas for how to send this to a Zebra printer?

### ISSUE THREAD

**Issue by SeaDude** [cod3monk/zpl#25]
Thanks for the Python translater for ZPL. This is very helpful.

Do you have any insights on how to remotely send the converted ZPL to an actual Zebra printer endpoint using Python? Seems like it REALLY involved. 

I'm aiming at a [TLP 2824 Plus](https://www.zebra.com/content/dam/zebra/manuals/printers/desktop/legacy/tlp2824-plus/tlp2824plus-ug-en.pdf).

**So far my research tells me:**

1. Printer must be setup with the [10/100 Zebra Print Server](https://support.zebra.com/cpws/docs/znet100/10100printserver_userguide.pdf)

2. From here, I see a couple methods of remotely pushing ZPL to the printer, though neither seem direct:
  - SMTP
  - POP3 to monitor an inbox (somehow!). 
 
3. But these introduce more moving parts

Any leads on how I can simplify remote printing?

Thanks!

**Comment by cod3monk** [comment]
I use the Zebra Print server and send raw ZPL to the TCP socket. Another option would be to hook the serial interface up to a RasPi and use socat to allow access to it via TCP. Both require direct network access to the printer.

I have not looked into mail delivery.

**Comment by WellingtonNico** [comment]
how do i send to a local printer, wich is not connected through internet, but its connected by cable on my computer?

**Comment by cod3monk** [comment]
Use `zpl.FilePrinter(filename)`, with `filename` referencing your device. For a USB connected printer this *could* be `/dev/ttyUSB0`, depending on your kernel configuration. Check `dmesg` or syslog when connecting the printer to find the appropriate filename.
Also, if using serial interfaces the device needs to be configured correctly in terms of Baude Rate using `stty`. If it's incorrect either garbage is produced or nothing will be received. Check printer configuration for correct setting.

**Comment by momoleinen** [comment]
Hello
I'm trying to print a text directly from a RasPy to a usb connected Zebra printer with 
"
conn = cups.Connection()
printers = conn.getPrinters()
printer=conn.getDefault()
with open('/home/pi/Documents/project/label.zpl', 'w') as f:
         f.write(l.dumpZPL())
conn.printFile(str(printer), '/home/pi/Documents/project/label.zpl' , 'label'. {"copies": "1"})
"
but it prints the zpl code not the text doesn't take into account the real label size

please help

**Comment by cod3monk** [comment]
Yes, cups will do the ZPL rendering for you. Thus it translates the textfile into a rendered version of the files content, just like viewing it with an editor.

If you want to use cups, you would need to pass the ZPL file as raw. On the command line this can be done via `lpr -P LPR_PRINTER_NAME -o raw`. I usually connect to the printer via a serial interface.

**Comment by momoleinen** [comment]
thanks for the quick response 
what I try to find out is how to send the "label" directly to the printer from python
the context is: after a signal is received on a GUI pin on the RasPy, I need to print a text on the label 

thanks
p.s. as you may have figured out, I'm a newb

**Comment by cod3monk** [comment]
for example with this code:
```python
import subprocess

LPR_PRINTER_NAME = "Zebra_GK420t"  # from cups config

with subprocess.Popen(
        ["lpr", "-P", LPR_PRINTER_NAME, "-o", "raw"], stdin=subprocess.PIPE
        ) as lpr:
    lpr.communicate(zpl)
```
