### ISSUE TITLE
QR code is omitting the first three characters

### ISSUE THREAD

**Issue by Humphreybas** [cod3monk/zpl#31]
The code `12334AB988765` as an example, scans as `34AB988765`  ->
![image](https://user-images.githubusercontent.com/2579891/168106124-a94c13ce-15e8-4860-a2b0-cb340b666e5b.png)

```import os
from PIL import Image
import zpl


def printlabel(title,code):
    l = zpl.Label(25,38)  #vertical, horizontal

    l.origin(27,2) #horizontal, vertical
    l.write_text("{}".format(title), char_height=3, char_width=1.5, line_width=25, justification='L',orientation='R')
    l.endorigin()

    qr_x = 9
    qr_y = 2
    l.origin(qr_x+3, qr_y) #horizontal, vertical
    l.write_barcode(height=1, barcode_type='Q', errorCorrection='H',magnification=6)
    l.write_text('{}'.format(code))
    l.endorigin()

    l.origin(qr_x,qr_y+1) #horizontal, vertical
    l.write_text("{}".format(code), char_height=2, char_width=1.5, line_width=25, justification='L',orientation='R')
    l.endorigin()


    #Debugging
    print(l.dumpZPL())
    l.preview()

if __name__ == '__main__':
    printlabel("Project: test",'12334AB988765')
```

**Comment by Humphreybas** [comment]
Ah I suddenly thought, maybe it's in the scanner, so I googled the problem, then I ended up on these [zebra forums](https://www.zebra.com/us/en/support-downloads/knowledge-articles/ait/QR-code-missing-first-three-characters-when-using-ZPL-language.html
)
so it's not the scanner, but it's the ZPL code

**Comment by cod3monk** [comment]
That is correct and how ZPL behaves:
The first three (or more) characters of a QR-Code datafield (`write_text()` following a `write_barcode(barcode_type='Q')`) configure the QR-Code. Checkout [page 125 and following of the ZPL2 manual](https://support.zebra.com/cpws/docs/zpl/13979l-010_ra.pdf#page=125).

Easiest would be to always start the data with `MA,` for standard reliability and automatic configuration, followed by the actual data you want to encode.

**Comment by Humphreybas** [comment]
So you are saying the users of this library should just configure the QR code in the first three characters themself?
Then what's the point of the function argument `def write_barcode(self,.......,errorCorrection='Q',....`? 
Isn't this library intended to do that three character configuration for the user based on the arguments of the `write_barcode()` call?

**Comment by cod3monk** [comment]
I agree that this is not ideal and am happy to take suggestions or pull requests :)

Inclusion of the payload data into `write_barcode` would be a solution, which could still be compatible with the current API.

This library is meant as a helper, but will never be able to replace knowledge of the underlying ZPL.

**Comment by Humphreybas** [comment]
Cool! I will try do a pull request soon.

I hope it doesn't come as a surprise that by using this library I am exactly trying to do that, avoiding to learn ZPL language haha.
