### ISSUE TITLE
Barcode Width

### ISSUE THREAD

**Issue by pathroz** [cod3monk/zpl#37]
is there an option to set the width of the barcode

**Comment by weinrank** [comment]
I have the same question, any updates?

**Comment by cod3monk** [comment]
No, that is not supported by ZPL. Check their reference manual: https://support.zebra.com/cpws/docs/zpl/1994_46469lr1.pdf

Details depend on the barcode type, but usually the hight can be set and the width depends both on the set height and the data length encoded.
