### ISSUE TITLE
regarding the conversion of rgb images to zpl

### ISSUE THREAD

**Issue by bhargav2496** [cod3monk/zpl#4]
I tried your python code for the given below image
![out](https://user-images.githubusercontent.com/38598709/48893464-70b84700-ee66-11e8-8f3c-aa0c5eb865aa.png)
when i try to print the image it gives the image as below
![capture1](https://user-images.githubusercontent.com/38598709/48893526-92193300-ee66-11e8-90cc-bc5e6a4a0fcc.JPG)
Any solution kindly provide.

**Comment by cod3monk** [comment]
The transformation of the image is completely outsourced to Pillow / PIL. The problem is that there are no grey scales and everything needs to be mapped to black or white pixels. Not sure if it could be done better. What would you expect the result to look like?

**Comment by bhargav2496** [comment]
![1542169259154 - copy](https://user-images.githubusercontent.com/38598709/48904514-9fddb100-ee84-11e8-92c5-a328e8510ca1.JPEG)
This is my expected result though this is not that image which I have asked but it should print in this format

**Comment by cod3monk** [comment]
You will need to preprocess the file using PIL or another library. Sorry about that.
