### ISSUE TITLE
QR-Code not showing the complete text

### ISSUE THREAD

**Issue by LeChatNoire93** [cod3monk/zpl#41]
I've bin trying to create QR Codes.  By verifying that the code is correct I have found out, that the first characters of the text are missing. 
This happens with the code from the example as well:

Calling this function:

def create_zebra_barcode() :

    l = Label(100,80)
    height = 0
    l.origin(0,0)
    l.write_text("Problem?", char_height=10, char_width=8, line_width=60, justification='C')
    l.endorigin()

    height += 20
    l.origin(22, height)
    l.write_barcode(height=None, barcode_type='Q', magnification=4)
    l.write_text('https://github.com/cod3monk/zpl')
    l.endorigin()

    height += 20
    l.origin(0, height)
    l.write_text('Happy Troloween!', char_height=5, char_width=4, line_width=60,
                 justification='C')
    l.endorigin()

    print(l.dumpZPL())
    l.preview()

Results in this zpl code:
^XA^FO0,0^A0N,120,96^FB720,1,0,C,0^FDProblem?\&^FS^FO264,240^BQN,2,4,Q,7^FDhttps://github.com/cod3monk/zpl^FS^FO0,480^A0N,60,48^FB720,1,0,C,0^FDHappy Troloween!\&^FS^XZ

If you are scanning the QR-Code the displayed text is: ps://github.com/cod3monk/zpl

**Comment by LeChatNoire93** [comment]
The result by using barcode() is the same.

**Comment by cod3monk** [comment]
This behaviour is intended as the `write_barcode()` function only issues the appropriate ZPL command.
Following a `^BQ` command (from `write_barcode()`) is the `^FD` (`write_text()`), but the first three characters configure the QR code. As you spotted correctly, they are not included in the QR-Data.
I would recommend using the `barcode()` function, which issued the `^FD` command automatically and also takes the payload to be encoded. The usage is shown in the README file.

If you still think that there is an issue, please reopen.
