### ISSUE TITLE
How to send the file to a USB connected printer on Windows

### ISSUE THREAD

**Issue by drzwave** [cod3monk/zpl#45]
I see the printer.py file but at the lowest level it relies on:
   def request_info(self, command):
        raise Exception("not implemented in this printer class")
so it would seem this is not yet implemented?

I am trying to print QR codes on small labels to a USB connected printer from a Win10 Nuc (like) miniPC.

Any suggestions/guidance would be appreciated.

**Comment by cod3monk** [comment]
Interfacing with USB Printers from Windows is currently not supported.

The `TCPPrinter` and `FilePrinter` classes implement this function. I am not sure how one may interact with a usb device, but I would suspect you will need to implement a `USBPrinter` class that uses Windows APIs. You could have a look at [pyusb](https://github.com/pyusb/pyusb), which seems to be what you need.

If you make progress on this, feel free to open a pull request.

**Comment by drzwave** [comment]
I solved sending the  ZPL file to a USB printer on Windows by using [Zebra](https://pypi.org/project/zebra/). 
Which is basically just using win32print to connect to the printer.
Would be nice if this functionality was in this repo so it can be a one-stop-shop.

**Comment by cod3monk** [comment]
Adding the zebra library as a printer class would be a nice addition. Happy to accept pull requests on this.
