### ISSUE TITLE
Font names

### ISSUE THREAD

**Issue by ildarakhmetov** [cod3monk/zpl#5]
Thanks for an amazing package, really helpful!

Just one issue. For UTF-8 characters (Cyrillic in my case), I use the font `E:TT0003M_.FNT`. However, I can't pass it to the `write_text()` function. It looks like there is a limit on single-char standard font names.

Would be awesome if you could lift that limit to enable use of other fonts.

**Comment by cod3monk** [comment]
Please test commit 34f9075 and reopen if problem still exists.

To install the latest version from git use: `pip install -U git+https://github.com/cod3monk/zpl`

**Comment by ildarakhmetov** [comment]
Please test GH-6 . With these minor edits, `write_text()` works fine with named fonts.

**Comment by cod3monk** [comment]
Merged. Thanks!

**Comment by ASchwad** [comment]
Hey guys,
is there an overview of the possible font names? For instance, i would like to use arial as font, but just using "arial" as font attribute is not recognized as valid font.

**Comment by cod3monk** [comment]
@ASchwad check the [ZPL2 Programming Manual](https://support.zebra.com/cpws/docs/zpl/13979l-010_ra.pdf) page 894 and following.
